# Lesson 7: Numpy

In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.array([1,2,3.1])

array([1. , 2. , 3.1])

In [4]:
np.array([1,2,"3"])

array(['1', '2', '3'], dtype='<U21')

In [5]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])

In [8]:
np.full((3,2),1)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.arange(1,11,3) #start, stop, step

array([ 1,  4,  7, 10])

In [11]:
x = np.linspace(0,1,5)

In [12]:
type(x)

numpy.ndarray

In [13]:
x 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
x.ndim

1

In [15]:
A = np.full((2,3),8)

In [16]:
x.shape

(5,)

In [17]:
A.shape

(2, 3)

In [18]:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array


In [19]:
x2 

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]], dtype=int32)

In [20]:
x2.size 

12

In [21]:
x.dtype

dtype('float64')

In [22]:
x2.dtype

dtype('int32')

In [23]:
x2 

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]], dtype=int32)

In [24]:
x2.itemsize

4

In [25]:
x2.nbytes

48

In [26]:
np.random.randint(10, size=(3, 4), dtype="int8").nbytes

12

In [27]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]], dtype=int32)

In [28]:
x2[:2,-2:]

array([[2, 4],
       [8, 8]], dtype=int32)

In [29]:
x2[:2,]

array([[3, 5, 2, 4],
       [7, 6, 8, 8]], dtype=int32)

In [30]:
x2[:2,:]

array([[3, 5, 2, 4],
       [7, 6, 8, 8]], dtype=int32)

In [31]:
x2[:,:3]

array([[3, 5, 2],
       [7, 6, 8],
       [1, 6, 7]], dtype=int32)

In [32]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]], dtype=int32)

In [33]:
x2_sub = x2[:2,:2]
x2_sub

array([[3, 5],
       [7, 6]], dtype=int32)

In [34]:
x2_sub[0,0] = 99
x2_sub 

array([[99,  5],
       [ 7,  6]], dtype=int32)

In [35]:
x2 

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]], dtype=int32)

In [36]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]], dtype=int32)

In [37]:
np.delete(x2,0,axis=1)

array([[5, 2, 4],
       [6, 8, 8],
       [6, 7, 7]], dtype=int32)

In [38]:
x2 

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]], dtype=int32)

In [39]:
np.append(x2,np.array([[ 4, 6, 7, 7]]), axis=0)

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7],
       [ 4,  6,  7,  7]])

In [40]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]], dtype=int32)

In [41]:
np.append(x2,np.array([[6], [7], [7]]), axis=1)

array([[99,  5,  2,  4,  6],
       [ 7,  6,  8,  8,  7],
       [ 1,  6,  7,  7,  7]])

In [42]:
np.array([[6], [7], [7]])

array([[6],
       [7],
       [7]])

In [43]:
x3 = np.arange(0,12)
x3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [44]:
x3.size 

12

In [45]:
x3.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
x3.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [47]:
x3.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
x3.reshape(-1,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [49]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]], dtype=int32)

In [50]:
x2.flatten()

array([99,  5,  2,  4,  7,  6,  8,  8,  1,  6,  7,  7], dtype=int32)

In [51]:
x4 = x3.reshape(2,2,-1)
x4

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [52]:
x4.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
x3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
x4

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [55]:
x4[0,0,0] =999
x4 

array([[[999,   1,   2],
        [  3,   4,   5]],

       [[  6,   7,   8],
        [  9,  10,  11]]])

In [56]:
x3 

array([999,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [57]:
arr1 = np.full((2,3),1)
arr2 = np.full((2,3), 9)

In [58]:
print(arr1)
print(arr2)

[[1 1 1]
 [1 1 1]]
[[9 9 9]
 [9 9 9]]


In [59]:
np.concat([arr1,arr2],axis=0)

array([[1, 1, 1],
       [1, 1, 1],
       [9, 9, 9],
       [9, 9, 9]])

In [60]:
np.concatenate([arr1,arr2],axis=0)

array([[1, 1, 1],
       [1, 1, 1],
       [9, 9, 9],
       [9, 9, 9]])

In [61]:
np.concat([arr1,arr2],axis=1)

array([[1, 1, 1, 9, 9, 9],
       [1, 1, 1, 9, 9, 9]])

In [62]:
np.concat([arr1,arr2],axis=None)

array([1, 1, 1, 1, 1, 1, 9, 9, 9, 9, 9, 9])

In [63]:
arr_a = np.arange(1,13).reshape(3,4)
arr_b = np.arange(1,9).reshape(2,-1)
arr_c = np.arange(1,7).reshape(3,-1)
print(arr_a)
print(arr_b)
print(arr_c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]]


In [64]:
np.vstack((arr_a,arr_b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [65]:
np.hstack((arr_a,arr_c))

array([[ 1,  2,  3,  4,  1,  2],
       [ 5,  6,  7,  8,  3,  4],
       [ 9, 10, 11, 12,  5,  6]])

In [66]:
np.concat([arr_a,arr_b], axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [67]:
np.concat([arr_a,arr_c], axis=1)

array([[ 1,  2,  3,  4,  1,  2],
       [ 5,  6,  7,  8,  3,  4],
       [ 9, 10, 11, 12,  5,  6]])

In [68]:
arr_1 = np.arange(1,13)
arr_1 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [69]:
np.split(arr_1,2)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]

In [70]:
np.split(arr_1,3)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

In [71]:
np.split(arr_1,4)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [72]:
np.split(arr_1,[2])

[array([1, 2]), array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])]

In [73]:
np.split(arr_1,[2,4,6])

[array([1, 2]), array([3, 4]), array([5, 6]), array([ 7,  8,  9, 10, 11, 12])]

In [74]:
arr_2  = np.arange(0,16).reshape(4,4)
arr_2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
np.split(arr_2, 2, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [76]:
np.split(arr_2, [1,2], axis=0)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [77]:
np.split(arr_2, 2, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [78]:
np.vsplit(arr_2,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [79]:
np.split(arr_2, 2, axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [80]:
# Tạo một mảng NumPy lớn 
arr = np.arange(1e6) 
# Sử dụng hàm tổng hợp của NumPy 
%timeit np.sum(arr)

1.58 ms ± 104 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [81]:
# Sử dụng hàm tích hợp sẵn của Python 
%timeit sum(arr) 

87.1 ms ± 1.59 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [83]:
np.arange(4).reshape(2,2)

array([[0, 1],
       [2, 3]])

In [86]:
np.arange(9).reshape(9,1)+ np.arange(4).reshape(1,4)

array([[ 0,  1,  2,  3],
       [ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11]])

In [88]:
np.random.seed(0)
arr = np.random.randint(1,20, size=(4,4))
arr 

array([[13, 16,  1,  4],
       [ 4,  8, 10, 19],
       [ 5,  7, 13,  2],
       [ 7,  8, 15, 18]], dtype=int32)

In [89]:
arr>3

array([[ True,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False],
       [ True,  True,  True,  True]])

In [90]:
arr[arr>3]

array([13, 16,  4,  4,  8, 10, 19,  5,  7, 13,  7,  8, 15, 18],
      dtype=int32)

In [91]:
np.random.seed(0)
arr1 = np.random.randint(10, size = (3,4))
arr1

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

**Exercises**
1. Are there any values greater than 8?
2. Counts the frequency of 3 in x.
3. The sum of the elements is greater than 3 of x.
4. Product of odd numbers of x
5. The Sum of the prime numbers of x
6. How many values less than 6 in each row?


In [96]:
#1
np.sum(arr1>8) 

np.int64(1)

In [ ]:
#2
np.sum(arr1 == 3)

np.int64(3)

In [101]:
#3
arr1[arr1>3].sum()

np.int64(43)

In [104]:
#4
arr1[arr1 %2 ==1].prod()

np.int64(297675)

In [108]:
#6 
np.sum(arr1<6, axis=1)

array([4, 2, 2])

In [109]:
from My_module import is_prime

In [118]:
arr1[arr1>1]

array([5, 3, 3, 7, 9, 3, 5, 2, 4, 7, 6], dtype=int32)

In [119]:
mask = list(map(is_prime, arr1[arr1>1]))
mask 

[True, True, True, True, False, True, True, True, False, True, False]

In [121]:
arr1[arr1>1][mask].sum()

np.int64(35)

In [114]:
list(map(lambda x: x**2, [1,2,3,4]))

[1, 4, 9, 16]

In [122]:
arr1

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [123]:
arr1[[1,2],:]

array([[7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [129]:
arr1[[0,2],:]

array([[5, 0, 3, 3],
       [2, 4, 7, 6]], dtype=int32)

In [141]:
arr2 = np.array([[10,40],
                 [30,20]])
arr2 

array([[10, 40],
       [30, 20]])

In [142]:
np.sort(arr2)

array([[10, 40],
       [20, 30]])

In [143]:
np.sort(arr2, axis=0)

array([[10, 20],
       [30, 40]])

In [144]:
np.sort(arr2, axis=1)

array([[10, 40],
       [20, 30]])

In [145]:
np.sort(arr2, axis=None)

array([10, 20, 30, 40])

In [147]:
np.sort(arr2.flatten())

array([10, 20, 30, 40])

In [148]:
arr2.flatten()

array([10, 40, 30, 20])

In [149]:
np.argsort(arr2.flatten())

array([0, 3, 2, 1])

In [150]:
np.sort(arr2.flatten())

array([10, 20, 30, 40])